### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by sublayerio** [entercosmos/record-gallery-card#1]
## General

- [x] Cover field: show image placeholder when there are no attachments
- [x] Cover field: not show indicators when there's just one attachment (2 or more)
- [x] Cover field: support cover & fit
- [x] Cover field: center the image when it is covered

## Fixes
- [ ] Rename cover to crop
- [ ] Don't attach mouse events for switching attachments if there's just one attachment

## Restructure

- [ ] Remove all fields as dependencies, instead implement fieldRenderer
